### ISSUE TITLE
 IE7 - iframe within iframe is unable to send messages to parent iframe. it instead pops up a new window with that url .

### ISSUE THREAD

**Issue by threepointone** [daepark/postmessage#1]
I'm guessing it has to do with this - http://thedesignspace.net/MT2archives/000472.html 
can you think of other possible workarounds, if not a fix?

**Comment by daepark** [comment]
Do you have a test case I can look at? Also, just want to make sure you are specifying the url of the target window (parent iframe) since IE7 does not support window.postMessage and have to use location hash to send messages. Also, it is a known issue that I've only tested on IE7 where the two windows are direct parent/child and the parent is the top most window: http://postmessage.freebaseapps.com/#issues

**Comment by threepointone** [comment]
I'll set up a testcase in a bit; but just to confirm, yes, I am specifying the target window url. 

Basically - parent->iframe1->iframe2. iframe2 cannot communicate to iframe1 when the setting "Navigate windows and frames across different domains" is set to 'disable' (which is the default setting). It instead opens up a new window with the url of iframe1 + the hash as sent by pm.

**Comment by daepark** [comment]
This is a known issue with IE7: http://postmessage.freebaseapps.com/#issues
